In [3]:
# Dependencies

import pandas as pd
import matplotlib
from sqlalchemy import create_engine

In [10]:
# CSV files that are being analyzed

policy_csv = "Resources/Data/Policy.csv"
policy_df = pd.read_csv(policy_csv)
policy_df.head()

,policy_id,country,type,gov_policy,detail,start_date,end_date
0,1,Korea,Alert,Infectious Disease Alert Level,Level 1 (Blue),2020-01-03,2020-01-19
1,2,Korea,Alert,Infectious Disease Alert Level,Level 2 (Yellow),2020-01-20,2020-01-27
2,3,Korea,Alert,Infectious Disease Alert Level,Level 3 (Orange),2020-01-28,2020-02-22
3,4,Korea,Alert,Infectious Disease Alert Level,Level 4 (Red),2020-02-23,NaN
4,5,Korea,Immigration,Special Immigration Procedure,from China,2020-02-04,NaN

In [9]:
testing_csv = "Resources/Data/Time.csv"
testing_df = pd.read_csv(testing_csv)
testing_df.head()

         date  time  test  negative  confirmed  released  deceased
0  2020-01-20    16     1         0          1         0         0
1  2020-01-21    16     1         0          1         0         0
2  2020-01-22    16     4         3          1         0         0
3  2020-01-23    16    22        21          1         0         0
4  2020-01-24    16    27        25          2         0         0

In [27]:
# New DataFrame for Policy.csv

new_policy = policy_df[["policy_id", "type", "detail", "start_date"]].copy()
policy_c = new_policy.rename(columns={"start_date": "date"})
policy_c

,policy_id,type,detail,date
0,1,Alert,Level 1 (Blue),2020-01-03
1,2,Alert,Level 2 (Yellow),2020-01-20
2,3,Alert,Level 3 (Orange),2020-01-28
3,4,Alert,Level 4 (Red),2020-02-23
4,5,Immigration,from China,2020-02-04
...,...,...,...,...
56,57,Transformation,On-site inspection of major logistics faciliti...,2020-05-29
57,58,Transformation,"Mandatory wearing of passenger mask domestic, ...",2020-05-27
58,59,Transformation,Drivers such as buses and taxis can refuse to ...,2020-05-26
59,60,Technology,new quick response (QR) code system this week ...,2020-06-10
60,61,Health,Gov't Extends Tightened Quarantine Measures in...,2020-05-28

In [14]:
# New dataFrame for time.csv (testing)

new_testing = testing_df[["date", "test", "negative", "confirmed", "released", "deceased"]].copy()
new_testing

           date     test  negative  confirmed  released  deceased
0    2020-01-20        1         0          1         0         0
1    2020-01-21        1         0          1         0         0
2    2020-01-22        4         3          1         0         0
3    2020-01-23       22        21          1         0         0
4    2020-01-24       27        25          2         0         0
..          ...      ...       ...        ...       ...       ...
158  2020-06-26  1232315   1200885      12602     11172       282
159  2020-06-27  1243780   1211261      12653     11317       282
160  2020-06-28  1251695   1219975      12715     11364       282
161  2020-06-29  1259954   1228698      12757     11429       282
162  2020-06-30  1273766   1240157      12800     11537       282

[163 rows x 6 columns]

### The results below, dsplay an average count of both confirmed and negative test results, as well as the number of patients that have been released, and the ones that have deceased. This allows us to see the effects of the implementation of policies to the virus testing rate.

In [33]:
# (Set both dataframes into one, and clean it up)

avgresults_df = pd.merge(left=new_testing, right=policy_c, left_on='date', right_on='date')
del avgresults_df["policy_id"]
avgresults_df

,date,test,negative,confirmed,released,deceased,type,detail
0,2020-01-20,1,0,1,0,0,Alert,Level 2 (Yellow)
1,2020-01-20,1,0,1,0,0,Technology,Patients Information
2,2020-01-28,116,97,4,0,0,Alert,Level 3 (Orange)
3,2020-02-04,607,462,16,0,0,Immigration,from China
4,2020-02-04,607,462,16,0,0,Health,1st EUA
5,2020-02-12,5624,4811,28,7,0,Immigration,from Hong Kong
6,2020-02-12,5624,4811,28,7,0,Immigration,from Macau
7,2020-02-12,5624,4811,28,7,0,Health,2nd EUA
8,2020-02-12,5624,4811,28,7,0,Technology,NaN
9,2020-02-23,26179,17520,602,18,6,Alert,Level 4 (Red)
10,2020-02-26,53553,31576,1261,24,12,Health,by Local Government
11,2020-02-27,66652,39318,1766,26,13,Health,3rd EUA
12,2020-02-27,66652,39318,1766,26,13,Health,4th EUA
13,2020-02-27,66652,39318,1766,26,13,Health,Public-Sale
14,2020-02-29,94055,55723,3150,28,17,Social,Strong
15,2020-03-02,109591,71580,4212,31,22,Education,Daycare Center for Children
16,2020-03-02,109591,71580,4212,31,22,Education,Kindergarten
17,2020-03-02,109591,71580,4212,31,22,Education,High School
18,2020-03-02,109591,71580,4212,31,22,Education,Middle School
19,2020-03-02,109591,71580,4212,31,22,Education,Elementary School
20,2020-03-04,136707,102965,5328,41,32,Health,Standard Operating Procedures
21,2020-03-07,178189,151802,6767,118,44,Technology,NaN
22,2020-03-08,188518,162008,7134,130,50,Technology,Public Mask Sales Information
23,2020-03-09,196618,171778,7382,166,51,Immigration,from Japan
24,2020-03-09,196618,171778,7382,166,51,Health,5-day Rotation System
25,2020-03-12,234998,209402,7869,333,66,Immigration,from Italy
26,2020-03-12,234998,209402,7869,333,66,Immigration,from Iran
27,2020-03-13,248647,222728,7979,510,67,Health,5th EUA
28,2020-03-15,268212,243778,8126,834,75,Immigration,from France
29,2020-03-15,268212,243778,8126,834,75,Immigration,from Germany
30,2020-03-15,268212,243778,8126,834,75,Immigration,from Spain
31,2020-03-15,268212,243778,8126,834,75,Immigration,from U.K.
32,2020-03-15,268212,243778,8126,834,75,Immigration,from Netherlands
33,2020-03-16,274504,251297,8236,1137,75,Immigration,from Europe
34,2020-03-19,307024,282555,8565,1947,91,Immigration,from all the countries
35,2020-03-22,331780,308343,8897,2909,104,Social,Strong
36,2020-04-01,421547,395075,9887,5567,165,Immigration,from all the countries
37,2020-04-09,494711,468779,10423,6973,204,Education,High School (3rd grade)
38,2020-04-09,494711,468779,10423,6973,204,Education,Middle School (3rd grade)
39,2020-04-13,518743,494815,10537,7447,217,Immigration,from U.S.
40,2020-04-16,538775,513894,10613,7757,229,Social,Relay Cheer Campaign in SNS
41,2020-04-16,538775,513894,10613,7757,229,Education,High School (2nd grade)
42,2020-04-16,538775,513894,10613,7757,229,Education,High School (1st grade)
43,2020-04-16,538775,513894,10613,7757,229,Education,Middle School (2nd grade)
44,2020-04-16,538775,513894,10613,7757,229,Education,Middle School (1st grade)
45,2020-04-16,538775,513894,10613,7757,229,Education,Elementary School (5th ~ 6th grade)
46,2020-04-16,538775,513894,10613,7757,229,Education,Elementary School (4th grade)
47,2020-04-20,563035,540380,10674,8114,236,Social,Weak
48,2020-04-20,563035,540380,10674,8114,236,Education,Elementary School (3rd grade)
49,2020-04-20,563035,540380,10674,8114,236,Education,Elementary School (1st ~ 2nd grade)
50,2020-04-27,601660,582027,10738,8764,243,Technology,on people who violate self-quarantine measures
51,2020-05-06,643095,624280,10806,9333,255,Social,Weak(1st)
52,2020-05-08,654863,635174,10822,9484,256,Administrative,administrative order to close bars and clubs
53,2020-05-16,740645,711265,11037,9851,262,Administrative,Gathering limited administrative orders for nu...
54,2020-05-21,788684,759473,11122,10135,264,Administrative,Ban on gathering for 2 weeks for all karaoke a...
55,2020-05-26,839475,806206,11225,10275,269,Transformation,Drivers such as buses and taxis can refuse to ...
56,2020-05-27,852876,820550,11265,10295,269,Transformation,"Mandatory wearing of passenger mask domestic, ..."
57,2020-05-28,868666,834952,11344,10340,269,Health,Gov't Extends Tightened Quarantine Measures in...
58,2020-05-29,885120,849161,11402,10363,269,Transformation,On-site inspection of major logistics faciliti...
59,2020-06-10,1051972,1013847,11902,10611,276,Technology,new quick response (QR) code system this week ...